### ISSUE TITLE
why "emit RaffleEnter(PLAYER)" from test?

### ISSUE THREAD

**Issue by oldpride** [Cyfrin/foundry-full-course-f23#880]
### Lesson

Lesson 9

### Could you please leave a link to the timestamp in the video where this error occurs? (You can right click a video and "copy video URL at current time")

https://youtu.be/sas02qSFZ74?t=18743

### Operating System

Windows

### Describe the bug

I am in Lesson 9. In the following test, I don't get why the test need to "emit RaffleEnter(PLAYER)"?

in test/unit/RaffleTest.s.sol
```
function testEmitsEventOnEntrance() public {
        // Arrange
        vm.prank(PLAYER);

        // Act / Assert
        vm.expectEmit(true, false, false, false, address(raffle));
        
        emit RaffleEnter(PLAYER); // todo: shuoldn't the next call emit?
        raffle.enterRaffle{value: raffleEntranceFee}();
    }
```

I ask this because the next call "raffle.enterRaffle{value: raffleEntranceFee}()" will emit the event,
in src/Raffle.sol
```
    function enterRaffle() public payable {
        // require(msg.value >= i_entranceFee, "Not enough value sent");
        // require(s_raffleState == RaffleState.OPEN, "Raffle is not open");
        if (msg.value < i_entranceFee) {
            revert Raffle__SendMoreToEnterRaffle();
        }
        if (s_raffleState != RaffleState.OPEN) {
            revert Raffle__RaffleNotOpen();
        }
        s_players.push(payable(msg.sender));
        // Emit an event when we update a dynamic array or mapping
        // Named events with the function name reversed
        emit RaffleEnter(msg.sender);
    }
```

**Comment by shrutic11** [comment]
According to the description of using the cheatcode vm.expectEmit();
The steps to use expectEmit() are:

Assert a specific log is emitted during the next call.

1. Call the cheat code, specifying whether we should check the first, second or third topic, and the log data (expectEmit() checks them all). Topic 0 is always checked.
2. Emit the event we are supposed to see during the next call.
3. Perform the call.

https://book.getfoundry.sh/cheatcodes/expect-emit?highlight=expectEmit#expectemit

If you run the test without the emit YOUR_EVENT statement, you get the following error:
```error
[FAIL. Reason: Expected an emit, but the call reverted instead. Ensure you're testing the happy path when using the `expectEmit` cheatcode.] 
```
Even though not written anywhere, my understanding is, the reason we emit the event after expectEmit()
 statement is for the test to know what kind of event will be emitted by the main contract, so that, it can compare the emit statement sent from the test with the emit statement coming from the main contract.

**Comment by oldpride** [comment]
thanks a lot. What you said totally makes sense. I watched Patrick's video back and forth, but couldn't understand it. yes, I removed the emit line too to test and the test failed. Now I understand.

Using emit to generated the expected event is much easier than manually code the expected event.

**Comment by oldpride** [comment]
that was it.
