### ISSUE TITLE
Add .srt subtitles

### ISSUE THREAD

**Issue by PatrickAlphaC** [Cyfrin/foundry-full-course-f23#9]
### Describe the enhancement

I have a `subtitles` folder where I will put the "raw" AI-generated subtitles. If someone would like to edit them, I will then upload them to YouTube so others can watch and understand easier!

**Comment by PatrickAlphaC** [comment]
I haven't put them in yet... If someone else wants to dump the videos into descript it _should_ be pretty easy...

**Comment by lostintime101** [comment]
@PatrickAlphaC I tried with Descript and a couple of others. They all require sign up for paid tier. Free tier won't accommodate such a long video. Descript seems to be the best from what I can tell.
![fadsfadsf](https://github.com/Cyfrin/foundry-full-course-f23/assets/92709487/6efa2761-2a77-4d22-880c-bb2e43b23159)
If you can cover the $30, I'll handle it. But maybe you already have a paid account, or you want to handle another way.

**Comment by PatrickAlphaC** [comment]
All good. I'm going to close this issue as Google's auto-subtitles seem to be good enough.

**Comment by lostintime101** [comment]
> All good. I'm going to close this issue as Google's auto-subtitles seem to be good enough.

Glad you found a solution that works!

**Comment by ChefAharoni** [comment]
> 

OpenAI actually share an amazing subtitles model called Whisper. Since you're using a MacOS, you can download a program called MacWhisper ([link](https://goodsnooze.gumroad.com/l/macwhisper)) by [Jordi Bruin](https://goodsnooze.gumroad.com/), who's an amazing developer.

I've payed for the full version, so I can help with that if needed.
